baseURL = "https://mecce-test.netlify.app/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "mecce test website"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "SCIP ADMIN"
description = "meta stuff"
[params.banner]
heading = "The New UMoMA Opens its Doors"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Test CMS website for MECCE"
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Get in touch"
[params.footer]
address = "123 Main Street <br> Downtown"
content = "Hi. Test text...."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About MECCE"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
